add: docker image
beejsbj/api3-ecosystem pull request #23
Opened 2023-07-12 12:04 UTC by AamirAlam

- Add docker image 
- Fix role checks
- Fix build service

2023-07-13 02:25 UTC, Ashar2shahid requested changes

2023-07-13 02:25 UTC, Ashar2shahid commented on Dockerfile
> +FROM node:18.16.0-alpine AS BUILD_IMAGE
I don't think we should be using alpine, see [this ](https://snyk.io/blog/choosing-the-best-node-js-docker-image/)for reference

2023-07-13 02:25 UTC, Ashar2shahid commented on Dockerfile
> +COPY --from=BUILD_IMAGE $APP_PATH/node_modules ./node_modules
I think we should be doing the installation within the docker image and not copying over files because builds occurring on Windows and mac would cause conflicts

2023-07-13 02:25 UTC, Ashar2shahid commented on server/utils/authenticated.ts
> +      //check token has correct role to access the resource for moderators and admins
why are we still using tokens?

2023-07-13 04:44 UTC, AamirAlam commented on Dockerfile
> +FROM node:18.16.0-alpine AS BUILD_IMAGE
Gotcha

2023-07-13 04:52 UTC, AamirAlam commented on Dockerfile
> +COPY --from=BUILD_IMAGE $APP_PATH/node_modules ./node_modules
This does not copy build from the local machine, 


I have created a MULTI STAGE build, 
it runs `yarn` , and install all dependency in `BUILD_IMAGE`, then copy it to`APP_IMAGE` for the final build 

BUILD_IMAGE -> APP_IMAGE 

`COPY --from=BUILD_IMAGE $APP_PATH/node_modules ./node_modules
`
this will copy the node_modules from BUILD_IMAGE layer to APP_IMAGE layer . 

Reason for using a multistage build is -: 

`reduces the number of dependencies and unnecessary packages in the image, reducing the attack surface and improving security`

2023-07-15 07:28 UTC, beejsbj commented on middleware/auth.ts
> +    return navigateTo("/login");
@AamirAlam keep the `query: { to: to.path }` as well, like that we can auto redirect them to wherever their intended destination was. add-dapp vs add-article or any other that might come up later.

2023-07-16 12:12 UTC, AamirAlam commented on server/utils/authenticated.ts
> +      //check token has correct role to access the resource for moderators and admins
to authenticate github webhooks

2023-07-16 16:51 UTC, Ashar2shahid approved these changes

2023-07-17 19:07 UTC, merged